name: 'SFTP Sync'
description: 'Sync repository with SFTP server'
inputs:
  username:
    description: 'SFTP User'
    required: true
    default: 'tom'
  host:
    description: 'SFTP Host'
    required: true
    default: 'localhost'
outputs:
  anothertest:
    description: 'An output test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.host }}
